url: https://dephiloper.github.io
baseurl:

# Site settings
title: Philipp Bönsch 
email: philippboensch@tuta.io 
description: "My name is Philipp nice to meet you!"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/philboensch
  - title: stack-overflow
    url: https://stackoverflow.com/users/10547035/boesh
  - title: linkedin
    url: https://linkedin.com/in/pboensch/
  - title: github
    url: https://github.com/dephiloper

# Build settings
markdown: kramdown
permalink: pretty
